sudo: false
language: cpp
os:
  - linux
  - osx
compiler:
  - gcc
  - clang
matrix:
  exclude:
    - os: linux
      compiler: clang
    - os: osx
      compiler: gcc
script:
  - cd src
  - if [ "$TRAVIS_OS_NAME" = "linux" ] && [ "$CXX" = "g++" ];   then make -j 2 ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ] && [ "$CXX" = "clang++" ]; then make mac  ; fi
