sudo: false
language: cpp
os:
  - linux
  - osx
compiler:
  - gcc
  - clang
matrix:
  exclude:
    - os: linux
      compiler: clang
    - os: osx
      compiler: gcc
script:
  - cd src
  - if [ "$TRAVIS_OS_NAME" = "linux" ] && [ "$CXX" = "g++" ];   then make CC=$CC CPP=$CXX -j 4 ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ] && [ "$CXX" = "clang++" ]; then make CC=$CC CPP=$CXX mac  ; fi
  - make check_full
