# WS20230512
#
# FULL CHECKS
#
# Run check_full_2 when a review is requested to a pull request (allows for manual running of check_full_2)
#

name: aflow++ inhouse build check_full_2
#c++ builds: https://github.community/t/conditional-matrices/17206
#env var: https://dev.to/mihinduranasinghe/working-with-environment-variables-github-actions-part-2-46po

#[CO20230516 - needed?]run-name: Full Checks

on: # Run when a reviewer is requested to a pull request (action performed on GitHub.com)
  workflow_dispatch:
  #[CO20230527 - check_full_2 depends on API, which can be very slow...]push:
  schedule:
    - cron: "0 0 1 * *"
jobs:
  check_full_2:
    runs-on: [self-hosted, Linux, X64]
    steps:
      - uses: actions/checkout@v3
      - name: make
        run: make -j $((`grep -c ^processor /proc/cpuinfo`-2)) -C src
      - name: make check_full_2
        run: |
          cd src
          make check_full_2
