name: AFLOW-src C++ build

on:
  push:
    branches: [ master, staging ]
  pull_request:
    branches: [ master, staging ]

jobs:
  build_ubuntu-18.04:
    runs-on: [ ubuntu-18.04 ]
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make -C src
    - name: make check_full
      run: make -C src check_full
  build_ubuntu-16.04:
    runs-on: [ ubuntu-16.04 ]
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make -C src
    - name: make check_full
      run: make -C src check_full
