name: AFLOW-src C++ build

on:
  push:
    branches: [ master, staging ]
  pull_request:
    branches: [ master, staging ]

jobs:
  build_ubuntu_1804:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make -C src
    - name: make check_full
      run: make -C src check_full
  build_ubuntu_1604:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make -C src
    - name: make check_full
      run: make -C src check_full
  build_mac_1100:
    runs-on: macos-11.0
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make -C src
    - name: make check_full
      run: make -C src check_full
  build_mac_1015:
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make -C src
    - name: make check_full
      run: make -C src check_full
